edit util

diff --git a/util/opsfile.yml b/util/opsfile.yml
--- a/util/opsfile.yml
+++ b/util/opsfile.yml
@@ -224,3 +224,20 @@ tasks:
           traefik.io/ingress-controller) echo "traefik" ;;
           *) echo "unknown" ;;
         esac
+
+  edit:
+    desc: edit the current tasks or a plugin
+    silent: true
+    cmds:
+      - code --version >/dev/null || dir "please install VSCode and add the cli 'code' to your PATH"
+      - |
+        DIR="$OPS_ROOT"
+        if test -n "{{._plugin_}}"
+        then DIR="${OPS_HOME}/olaris-{{._plugin_}}"
+             if ! test -d "$DIR"
+             then echo "$DIR"
+                  echo "Plugin {{._plugin_}} not found - install it with ops -plugin <repo>"
+                  exit 1
+             fi
+        fi
+        code "$DIR"
