Support a lib folder

diff --git a/ide/nodejs/opsfile.yml b/ide/nodejs/opsfile.yml
--- a/ide/nodejs/opsfile.yml
+++ b/ide/nodejs/opsfile.yml
@@ -41,13 +41,29 @@ tasks:
     - "{{.DIR}}/package.json"
     generates:
     - "{{.DIR}}/node_modules/.package-lock.json"
-
+  
   action:
     silent: false
     desc: build the action updating the zip
     requires: {var: [DIR]}
-    dir: "{{.DIR}}"
     cmds:
-    - test -d "{{.DIR}}" || die "{{.DIR}} not found or not a directory"
-    - 7zz a {{.DIR}}.zip * -tzip -x!node_modules/* >/dev/null
-    - test -f "{{.DIR}}".zip || die "{{.DIR}}.zip not generated"
+      - test -d "{{.DIR}}" || die "{{.DIR}} not found or not a directory"
+      - |
+        ZIP_PATH="{{.DIR}}.zip"
+        DIR_ABS=$(realpath "{{.DIR}}")
+        ROOT_DIR=$(dirname "$(dirname "$DIR_ABS")")
+        LIB_DIR=$(dirname "$ROOT_DIR")/lib/nodejs
+
+        cd "$DIR_ABS"
+        zip -r "$ZIP_PATH" . -x "node_modules/*" -x "$(basename "$ZIP_PATH")"
+
+        if [ -d "$LIB_DIR" ]; then
+          cd "$LIB_DIR"
+          zip -ur "$ZIP_PATH" .
+        else
+          echo "$LIB_DIR not found, skip add"
+        fi
+
+        if [ ! -f "$ZIP_PATH" ]; then
+          die "$ZIP_PATH not created"
+        fi
diff --git a/ide/python/opsfile.yml b/ide/python/opsfile.yml
--- a/ide/python/opsfile.yml
+++ b/ide/python/opsfile.yml
@@ -43,13 +43,33 @@ tasks:
     - "{{.DIR}}/virtualenv/date"
 
   action:
-    silent: true
+    silent: false
     desc: compile
     requires: {var: [DIR]}
-    dir: "{{.DIR}}"
     cmds:
-    - test -d "{{.DIR}}" || die "{{.DIR}} not found or not a directory"
-    - 7zz a {{.DIR}}.zip * -tzip -x!virtualenv/* -x!requirements.txt >/dev/null
+      - test -d "{{.DIR}}" || die "{{.DIR}} not found or not a directory"
+      - |
+        ZIP_PATH="{{.DIR}}.zip"
+        DIR_ABS=$(realpath "{{.DIR}}")
+        ROOT_DIR=$(dirname "$(dirname "$DIR_ABS")")
+        LIB_DIR=$(dirname "$ROOT_DIR")/lib/python
+
+        echo "DIR_ABS=$DIR_ABS"
+        echo "LIB_DIR=$LIB_DIR"
+
+        cd "$DIR_ABS"
+        zip -r "$ZIP_PATH" . -x "virtualenv/*" -x "requirements.txt" -x "$(basename "$ZIP_PATH")"
+
+        if [ -d "$LIB_DIR" ]; then
+          cd "$LIB_DIR"
+          zip -ur "$ZIP_PATH" .
+        else
+          echo "$LIB_DIR not found, skip add"
+        fi
+
+        if [ ! -f "$ZIP_PATH" ]; then
+          die "$ZIP_PATH non created"
+        fi
 
   cli:
     silent: true
